server:
  port: 8081
  servlet:
    context-path: /tujipange
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tujipange
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
token.sign.key : "123$jwt.K"