server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tujipange
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
